#!/usr/bin/env python3
"""Validate the directory structure generated by otter assign.

Input: output directory path (e.g., dist/), optional --config path to instructor notebook
       for extracting expected companion files from ASSIGNMENT CONFIG.
Output: JSON to stdout with status and per-check results.

Checks that dist/autograder/ and dist/student/ exist with expected contents:
notebook, autograder zip, otter_config.json, and companion files.
"""

import json
import sys
import zipfile
from pathlib import Path


def extract_companion_files(config_notebook_path):
    """Read the instructor notebook and extract files: list from ASSIGNMENT CONFIG."""
    try:
        with open(config_notebook_path, "r", encoding="utf-8") as f:
            nb = json.load(f)
    except (json.JSONDecodeError, FileNotFoundError):
        return []

    cells = nb.get("cells", [])
    if not cells:
        return []

    # Cell 0 should be the ASSIGNMENT CONFIG raw cell
    cell0 = cells[0]
    source = "".join(cell0.get("source", []))
    if "# ASSIGNMENT CONFIG" not in source:
        return []

    # Simple YAML parsing for files: list
    files = []
    in_files = False
    for line in source.split("\n"):
        stripped = line.strip()
        if stripped.startswith("files:"):
            in_files = True
            continue
        if in_files:
            if stripped.startswith("- "):
                files.append(stripped[2:].strip())
            elif stripped and not stripped.startswith("#"):
                break  # End of files: block
    return files


def validate(output_dir, config_notebook=None):
    output_dir = Path(output_dir)
    checks = []

    # 1. autograder directory
    ag_dir = output_dir / "autograder"
    checks.append({
        "name": "autograder_dir_exists",
        "status": "pass" if ag_dir.is_dir() else "fail",
    })

    # 2. student directory
    st_dir = output_dir / "student"
    checks.append({
        "name": "student_dir_exists",
        "status": "pass" if st_dir.is_dir() else "fail",
    })

    # 3. autograder notebook
    ag_notebooks = list(ag_dir.glob("*.ipynb")) if ag_dir.is_dir() else []
    check = {"name": "autograder_notebook", "status": "fail"}
    if ag_notebooks:
        check["status"] = "pass"
        check["path"] = str(ag_notebooks[0])
    checks.append(check)

    # 4. autograder zip
    ag_zips = (list(ag_dir.glob("*-autograder_*.zip")) +
               list(ag_dir.glob("*autograder*.zip"))) if ag_dir.is_dir() else []
    check = {"name": "autograder_zip", "status": "fail"}
    if ag_zips:
        zp = ag_zips[0]
        # Verify zip is valid and non-empty
        try:
            with zipfile.ZipFile(zp, "r") as zf:
                if zf.namelist():
                    check["status"] = "pass"
                    check["path"] = str(zp)
                else:
                    check["message"] = "Autograder zip is empty"
        except zipfile.BadZipFile:
            check["message"] = "Autograder zip is corrupt"
    checks.append(check)

    # 5. otter_config.json
    otter_cfg = ag_dir / "otter_config.json" if ag_dir.is_dir() else Path("/nonexistent")
    checks.append({
        "name": "otter_config_json",
        "status": "pass" if otter_cfg.is_file() else "fail",
    })

    # 6. student notebook
    st_notebooks = list(st_dir.glob("*.ipynb")) if st_dir.is_dir() else []
    check = {"name": "student_notebook", "status": "fail"}
    if st_notebooks:
        check["status"] = "pass"
        check["path"] = str(st_notebooks[0])
    checks.append(check)

    # 7. companion files in both directories (if config notebook provided)
    companion_files = []
    if config_notebook:
        companion_files = extract_companion_files(config_notebook)

    if companion_files:
        missing_ag = [f for f in companion_files if not (ag_dir / f).exists()] if ag_dir.is_dir() else companion_files
        missing_st = [f for f in companion_files if not (st_dir / f).exists()] if st_dir.is_dir() else companion_files
        all_present = not missing_ag and not missing_st

        check = {
            "name": "companion_files",
            "status": "pass" if all_present else "fail",
            "expected": companion_files,
        }
        if missing_ag:
            check["missing_in_autograder"] = missing_ag
        if missing_st:
            check["missing_in_student"] = missing_st
        checks.append(check)

    overall = "pass" if all(c["status"] == "pass" for c in checks) else "fail"

    return {
        "status": overall,
        "checks": checks,
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Validate otter assign output structure")
    parser.add_argument("output_dir", help="Path to dist/ directory")
    parser.add_argument("--config", default=None,
                        help="Path to instructor notebook for companion file extraction")
    args = parser.parse_args()

    result = validate(args.output_dir, args.config)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
